### ISSUE TITLE
Misspecified head

### ISSUE THREAD

**Issue by kirilklein** [FGA-DIKU/EHR#252]
In our test finetune configs, we still specify the head as:

```
model:
  cls:
    _target_: ehr2vec.model.heads.ClassifierGRU
    bidirectional: true
```
However in the code we always use BiGRU. 
Current solution: Remove this from the test configs as to avoid confusion.
