### ISSUE TITLE
**Title: Exclude Specific Codes from Delayed Censoring**

### ISSUE THREAD

**Issue by kirilklein** [FGA-DIKU/EHR#273]
**Current**

```yaml
concept_pattern_hours_delay:
  "^D": 72
```

**Goal**
Delay all diagnosis codes by 72 h *except* lung-cancer codes (`DC*`), which should be censored immediately.

**Proposed**

```yaml
concept_pattern_hours_delay:
  codes:
    "^D": 72      # 72 h delay for diagnoses
  exclude:
    - "^D/DC.*"   # immediate censoring for lung-cancer codes
```

**Logic**

1. If code matches any `exclude` pattern → delay = 0
2. Else if it matches a `codes` pattern → apply specified delay
3. Else → no delay (default)
